# -*- coding: utf-8 -*-
"""account_balance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLmtqa3Vj07afnNAJ3S-ndjBMfGONA0Z
"""

#CS175
#Lucas Vandenakker
#account_balance

startValue = 1000
interestRate = 0.05
year1 = startValue + (startValue*interestRate)
year2 = year1 + (year1*interestRate)
year3 = year2 + (year2*interestRate)

print(f"The account starts with ${startValue:,}")
print(f"After the first year the value is ${year1:,.2f}")
print(f"After the first year the value is ${year2:,.2f}")
print(f"After the first year the value is ${year3:,.2f}")