# -*- coding: utf-8 -*-
"""f_to_c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLmtqa3Vj07afnNAJ3S-ndjBMfGONA0Z
"""

#CS175
#Lucas Vandenakker
#f_to_c

tempF = float(input("Input the temperature (Fahrenheit)"))

tempC = (tempF - 32) * 5/9

print(tempF, "°F is", tempC, "°C")