# -*- coding: utf-8 -*-
"""format_print

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLmtqa3Vj07afnNAJ3S-ndjBMfGONA0Z
"""

#CS175
#Lucas Vandenakker
#format_print

num1 = 1.8
num2 = 12.9
num3 = 2
num4 = 100.25

print(f"{num1:.2f} \n{num2:.2f} \n{num3:.2f} \n{num4:.2f}")