# -*- coding: utf-8 -*-
"""math_ops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLmtqa3Vj07afnNAJ3S-ndjBMfGONA0Z
"""

#CS175
#Lucas Vandenakker
#math_ops

num1 = int(input("Please enter interger one: "))
num2 = int(input("Please enter interger two: "))

print("The sum:", (num1+num2))
print("The difference:", (num1-num2))
print("The product:", (num1*num2))
print("The average:", ((num1+num2)/2))
print("The distance:", (abs(num1-num2)))
print("The maximum:", max(num1,num2))
print("The minimum:", min(num1,num2))