# -*- coding: utf-8 -*-
"""name_printer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLmtqa3Vj07afnNAJ3S-ndjBMfGONA0Z
"""

#CS175
#Lucas Vandenakker
#name_printer

print("+-------+")
print("| Lucas |")
print("+-------+")