# -*- coding: utf-8 -*-
"""print_grid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLmtqa3Vj07afnNAJ3S-ndjBMfGONA0Z
"""

#CS175
#Lucas Vandenakker
#print_grid

line1 = "+--+--+--+"
line2 = "|  |  |  |"

print(line1, line2, line1, line2,line1,line2,line1, sep='\n')