# -*- coding: utf-8 -*-
"""stocks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdwzRSC6Js5a6YM43y055r1i-YE-53DC
"""

COMMISSION_RATE = float(input("Enter commission rate percentage (ex 0.03) on stock purchase: "))
COMMISSION_RATE_SALE = float(input("Enter commission rate percentage (ex 0.03) on stock sale: "))
NUM_SHARES = int(input("Enter number of shares purchased: "))
NUM_SOLD = int(input("Enter number of shares sold: "))
PURCHASE_PRICE = float(input("Enter purchase price per share: "))
SELLING_PRICE = float(input("Enter sell price per share: "))


amountPaidForStock = (NUM_SHARES * PURCHASE_PRICE)
purchaseCommission = (COMMISSION_RATE * amountPaidForStock)

totalPaid = (amountPaidForStock + purchaseCommission)
stockSoldFor = (NUM_SOLD * SELLING_PRICE)

sellingCommission = (COMMISSION_RATE_SALE * stockSoldFor)
totalReceived = (stockSoldFor - sellingCommission)
profitOrLoss = (totalReceived - totalPaid)

print(f"Amount paid for the stock: ${amountPaidForStock}")
print(f"Commission paid on the purchase:${purchaseCommission}")
print(f"Amount the stock sold for: ${stockSoldFor}")
print(f"Commission paid on the sale: ${sellingCommission}")
print(f"Profit (or loss if negative): ${profitOrLoss}")



